=== niklasgerdt/messagingLibraryEvaluationWithJava8/src/main/resources/SimulationSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com"
	elementFormDefault="qualified">

	<xs:element name="simulation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="system-under-test" type="xs:string" />
				<xs:element name="simulators">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="simulator">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:integer" />
										<xs:element name="name" type="xs:string" />
										<xs:element name="event-content-length" type="xs:integer"
											default="100" />
										<xs:element name="pause-between-events" type="xs:integer"
											default="10000" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== niklasgerdt/messagingLibraryEvaluationWithJava8/src/main/resources/simulations/Simulation.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:simulation xmlns:p="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.w3schools.com ../SimulationSchema.xsd ">

  <p:system-under-test>jerotest</p:system-under-test>
  <p:simulators>
    <p:simulator>
      <p:id>0</p:id>
      <p:name>nyse</p:name>
      <p:event-content-length>100</p:event-content-length>
      <p:pause-between-events>1000</p:pause-between-events>
    </p:simulator>
    <p:simulator>
      <p:id>1</p:id>
      <p:name>nasdaq</p:name>
      <p:event-content-length>100</p:event-content-length>
      <p:pause-between-events>10000</p:pause-between-events>
    </p:simulator>
    <p:simulator>
      <p:id>3</p:id>
      <p:name>reuters</p:name>
      <p:event-content-length>100000</p:event-content-length>
      <p:pause-between-events>1000000</p:pause-between-events>
    </p:simulator>
  </p:simulators>
  <p:listeners>
    <p:listener>
      <p:id>0</p:id>
    </p:listener>
    <p:listener>
      <p:id>1</p:id>
    </p:listener>
  </p:listeners>
</p:simulation>

=== niklasgerdt/messagingLibraryEvaluationWithJava8/src/main/resources/simulations/SimulationNoEventService.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:simulation xmlns:p="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com ../SimulationSchema.xsd ">

	<p:system-under-test>performance-without-actual-eventservice</p:system-under-test>
	<p:simulators>
		<p:simulator>
			<p:id>1</p:id>
			<p:event-content-length>100</p:event-content-length>
			<p:pause-between-events>0</p:pause-between-events>
		</p:simulator>
	</p:simulators>
	<p:listeners>
		<p:listener>
			<p:id>1</p:id>
		</p:listener>
	</p:listeners>
</p:simulation>

=== niklasgerdt/messagingLibraryEvaluationWithJava8/src/main/resources/simulations/SimulationSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:simulation xmlns:p="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com SimulationSchema.xsd ">
	<p:name>p:name</p:name>
	<p:system-under-test>p:system-under-test</p:system-under-test>
	<p:simulators>
		<p:simulator>
			<p:id>0</p:id>
			<p:name>0</p:name>
			<p:event-content-length>100</p:event-content-length>
			<p:pause-between-events>10000</p:pause-between-events>
		</p:simulator>
		<p:simulator>
			<p:id>1</p:id>
			<p:name>1</p:name>
			<p:event-content-length>100</p:event-content-length>
			<p:pause-between-events>10000</p:pause-between-events>
		</p:simulator>
	</p:simulators>
</p:simulation>

=== niklasgerdt/messagingLibraryEvaluationWithJava8/src/main/resources/simulations/TestSimulation.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="src/main/resources/SimulationSchema.xsd">

	<name></name>
	<system-under-test>test</system-under-test>
	<simulators>
		<simulator>
			<id>1</id>
			<name>test</name>
			<event-content-length>100</event-content-length>
			<pause-between-events>10000</pause-between-events>
		</simulator>
	</simulators>
</simulation>
